# Generated by Django 2.2.11 on 2020-04-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200412_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistmodel',
            old_name='product',
            new_name='name',
        ),
    ]
