# Generated by Django 2.2.11 on 2020-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_wishlistmodel_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistmodel',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True, verbose_name='Продукт'),
        ),
    ]
