# Generated by Django 2.2.11 on 2020-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20200412_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='brend',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='tkan',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ткань'),
        ),
    ]
