# Generated by Django 2.2.11 on 2020-04-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20200412_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='brend',
        ),
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='tkan',
        ),
    ]
