# Generated by Django 2.2.11 on 2020-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_auto_20200413_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена 1,5'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена 2'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='price_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена семья'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='price_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена Евро'),
        ),
    ]
