# Generated by Django 2.2.11 on 2020-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_auto_20200417_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Категория'),
        ),
    ]
