# Generated by Django 2.2.11 on 2020-03-15 18:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='Транслит')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Транслит')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Category', verbose_name='Родитель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=product.models.image_folder, verbose_name='Фотка')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит(Не трогать)')),
                ('price_polutorca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена полуторка')),
                ('price_old_polutorca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена полуторка')),
                ('price_dvuspal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена двухспального')),
                ('price_old_dvuspal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена двухспального')),
                ('price_semeuka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена семейка')),
                ('price_old_semeuka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена семейки')),
                ('price_euro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена evro')),
                ('price_old_euro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена evro')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст')),
                ('description_short', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст(короткий)')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии')),
                ('new_product', models.BooleanField(default=False, verbose_name='Новинка')),
                ('top', models.BooleanField(default=False, verbose_name='В топе(на гл.странице)')),
                ('slider', models.BooleanField(default=False, verbose_name='Слайдер(на гл.странице)')),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('brend', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brend', to_field='slug', verbose_name='Бренд')),
                ('categ', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='product.Category', to_field='slug', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Tkan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='Транслит')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткань',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=product.models.image_gallary_folder)),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tkan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Tkan', to_field='slug', verbose_name='Ткань'),
        ),
    ]
