# Generated by Django 2.2.11 on 2020-04-27 17:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200413_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mta_d',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=120, null=True, unique=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='mta_k',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
    ]
