# Generated by Django 2.2.11 on 2020-09-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gostinye', '0003_auto_20200428_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Серия')),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True, verbose_name='Транслит')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серия',
            },
        ),
        migrations.AddField(
            model_name='gostinyemodel',
            name='seria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gostinye.Seria', to_field='slug', verbose_name='Серия'),
        ),
    ]
