# Generated by Django 2.2.11 on 2020-09-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prihozhie', '0005_auto_20200926_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widthtumbforshues',
            options={'verbose_name': 'Ширина тумбы для обуви', 'verbose_name_plural': 'Ширина тумбы для обуви'},
        ),
    ]
