# Generated by Django 2.2.11 on 2020-09-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prihozhie', '0006_auto_20200926_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prihozhiemodel',
            name='widthforshues',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prihozhie.WidthTumbForShues', to_field='name', verbose_name='Ширина тумбы для обуви'),
        ),
    ]
