# Generated by Django 2.2.11 on 2020-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detskie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detskiemodel',
            name='photoMenu',
            field=models.BooleanField(default=False, verbose_name='Фото в меню'),
        ),
    ]
