# Generated by Django 2.2.11 on 2020-04-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='key_descriptin',
            new_name='key_description',
        ),
    ]
