# Generated by Django 2.2.11 on 2020-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200410_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keyword',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Ключи'),
        ),
    ]
