# Generated by Django 2.2.11 on 2020-04-08 08:15

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigSliderImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Название категории')),
                ('lozung', models.CharField(blank=True, max_length=120, null=True, verbose_name='Рекламный текст')),
                ('brendi', models.CharField(blank=True, max_length=120, null=True, verbose_name='Торг.марки')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=home.models.image_gallary_folder)),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
