# Generated by Django 2.2.11 on 2020-04-08 12:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=home.models.image_gallary_folder)),
                ('text', models.SlugField(blank=True, default=None, null=True, verbose_name='Текст1')),
                ('text2', models.SlugField(blank=True, default=None, null=True, verbose_name='Текст2')),
                ('link', models.SlugField(blank=True, default=None, null=True, verbose_name='ссылка')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
