# Generated by Django 2.2.11 on 2020-04-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_advertisingimagemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingimagemodel',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='advertisingimagemodel',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Текст1'),
        ),
        migrations.AlterField(
            model_name='advertisingimagemodel',
            name='text2',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Текст2'),
        ),
    ]
