# Generated by Django 2.2.11 on 2020-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200408_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingimagemodel',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит'),
        ),
    ]
