# Generated by Django 2.2.11 on 2020-04-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derevyannayamebel', '0002_derevyannayamebelmodel_photomenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='derevyannayamebelmodel',
            name='mta_d',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='derevyannayamebelmodel',
            name='mta_k',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
    ]
