# Generated by Django 2.2.11 on 2020-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derevyannayamebel', '0003_auto_20200427_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='mta_d',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='brend',
            name='mta_k',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='podcateg',
            name='mta_d',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='podcateg',
            name='mta_k',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
    ]
