# Generated by Django 2.2.11 on 2020-04-27 17:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derevyannayamebel', '0004_auto_20200427_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcateg',
            name='mta_d',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=120, null=True, unique=True, verbose_name='Мета описание'),
        ),
    ]
