# Generated by Django 2.2.11 on 2020-04-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derevyannayamebel', '0007_auto_20200427_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derevyannayamebelmodel',
            name='mta_d',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='derevyannayamebelmodel',
            name='mta_k',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ключевые слова'),
        ),
    ]
