# Generated by Django 2.2.11 on 2020-04-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derevyannayamebel', '0008_auto_20200427_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derevyannayamebelmodel',
            old_name='mta_d',
            new_name='mtad',
        ),
        migrations.RenameField(
            model_name='derevyannayamebelmodel',
            old_name='mta_k',
            new_name='mtak',
        ),
    ]
