# Generated by Django 2.2.11 on 2020-04-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derevyannayamebel', '0010_auto_20200427_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='derevyannayamebelmodel',
            name='keyword',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Ключи'),
        ),
    ]
