# Generated by Django 2.2.11 on 2020-10-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skafi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skafmodel',
            name='price_shelf_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена пенала 0,450мм'),
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='price_shelf_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена пенала 0,600мм'),
        ),
        migrations.AlterField(
            model_name='skafmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена шкафа'),
        ),
    ]
