# Generated by Django 2.2.11 on 2020-10-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skafi', '0002_auto_20201005_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Height_penal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Высота пенала')),
            ],
            options={
                'verbose_name': 'Высота пенала',
                'verbose_name_plural': 'Высота пенала',
            },
        ),
        migrations.CreateModel(
            name='Width_penal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Ширина_пенала')),
            ],
            options={
                'verbose_name': 'Ширина пенала',
                'verbose_name_plural': 'Ширина пенала',
            },
        ),
        migrations.AlterModelOptions(
            name='height',
            options={'verbose_name': 'Высота шкафа', 'verbose_name_plural': 'Высота шкафа'},
        ),
        migrations.AlterModelOptions(
            name='width',
            options={'verbose_name': 'Ширина шкафа', 'verbose_name_plural': 'Ширина шкафа'},
        ),
        migrations.AlterField(
            model_name='height',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Высота шкафа'),
        ),
        migrations.AlterField(
            model_name='width',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Ширина шкафа'),
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='height_penal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='skafi.Height_penal', to_field='name', verbose_name='Высота пенала'),
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='width_penal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='skafi.Width_penal', to_field='name', verbose_name='Ширина пенала'),
        ),
    ]
