# Generated by Django 2.2.11 on 2020-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skafi', '0004_auto_20201005_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skafmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='price_g450_od',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ш450od '),
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='price_g450_st',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ш450st'),
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='price_g600_od',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ш600od '),
        ),
        migrations.AddField(
            model_name='skafmodel',
            name='price_g600_st',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена ш600st'),
        ),
    ]
