# Generated by Django 2.2.11 on 2020-04-21 13:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import spalni.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20200413_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Глубина')),
            ],
            options={
                'verbose_name': 'Глубина',
                'verbose_name_plural': 'Глубина',
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Высота',
                'verbose_name_plural': 'Высота',
            },
        ),
        migrations.CreateModel(
            name='Podcateg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Транслит')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True, unique=True, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Ширина',
                'verbose_name_plural': 'Ширина',
            },
        ),
        migrations.CreateModel(
            name='SpalniModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Название')),
                ('image_1', models.ImageField(blank=True, default=None, null=True, upload_to=spalni.models.image_folder, verbose_name='Фотка1')),
                ('image_2', models.ImageField(blank=True, default=None, null=True, upload_to=spalni.models.image_folder, verbose_name='Фотка2')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит(Не трогать)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст')),
                ('description_short', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Текст(короткий)')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии')),
                ('new_product', models.BooleanField(default=False, verbose_name='Новинка')),
                ('top', models.BooleanField(default=False, verbose_name='В топе(на гл.странице)')),
                ('slider', models.BooleanField(default=False, verbose_name='Слайдер(на гл.странице)')),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('brend', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spalni.Brend', to_field='name', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', to_field='slug', verbose_name='Категория')),
                ('depth', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spalni.Depth', to_field='name', verbose_name='Глубина')),
                ('height', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spalni.Height', to_field='name', verbose_name='Высота')),
                ('podcateg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spalni.Podcateg', to_field='slug', verbose_name='Подкатегория')),
                ('width', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spalni.Width', to_field='name', verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SpalniImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=spalni.models.image_gallary_folder)),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Транслит')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spalni.SpalniModel')),
            ],
        ),
    ]
