# Generated by Django 2.2.11 on 2020-04-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCabinet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='customer_surname',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='customer_tel',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тел.'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Созд.'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обнов.'),
        ),
    ]
