# Generated by Django 2.2.11 on 2020-04-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCabinet', '0002_auto_20200404_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='token',
            new_name='token_key',
        ),
    ]
