# Generated by Django 2.2.11 on 2020-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_productinordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasketmodel',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Кол.во'),
        ),
    ]
