# Generated by Django 2.2.11 on 2020-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200322_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinordermodel',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Размер'),
        ),
    ]
