# Generated by Django 2.2.11 on 2020-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_productinordermodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinordermodel',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Фото'),
        ),
    ]
