# Generated by Django 2.2.11 on 2020-04-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_productinordermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinordermodel',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', to_field='name'),
        ),
    ]
