# Generated by Django 2.2.11 on 2020-04-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_productinbasketmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasketmodel',
            name='product',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Продукт'),
        ),
    ]
