# Generated by Django 2.2.11 on 2020-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200423_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasketmodel',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Цвет фасада'),
        ),
        migrations.AddField(
            model_name='productinordermodel',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Цвет фасада'),
        ),
    ]
